### ISSUE TITLE
Use WP-CLI docker image

### ISSUE THREAD

**Issue by dingo-d** [isBatak/nextpress#4]
Looking at your `docker-compose.yml` for backend, I'm not 100% sure why you are using the Dockerfile for this.

Wouldn't an official image suffice + wpcli installation using

```yml
  cli:
    image: wordpress:cli
    user: xfs
    volumes:
      - wordpress_data:/var/www/html
      - .:/var/www/html/wp-content/plugins/gutenberg
    depends_on:
      - mysql
      - wordpress
```

You can look how the compose file looks in the gutenberg repo:

https://github.com/WordPress/gutenberg/blob/master/docker-compose.yml
